### PR TITLE
bump adbc  0.11.0

### LINKED ISSUE #60: v 0.3.0 does not download postgres driver successfully in livebook
Steps to reproduce

open new notebook and download v `0.3.0` of adbc

in new cell try to download postgres driver

`Adbc.download_driver!(:postgresql)`

get error
```
** (RuntimeError) could not download Adbc driver for postgresql: couldn't fetch file from https://github.com/apache/arrow-adbc/releases/download/apache-arrow-adbc-0.11.0-rc0/adbc_driver_postgresql-0.11.0-py3-none-macosx_11_0_arm64.whl: {:ok, {{~c"HTTP/1.1", 404, ~c"Not Found"}, [{~c"cache-control", ~c"no-cache"}, {~c"date", ~c"Thu, 04 Apr 2024 01:29:25 GMT"}, {~c"server", ~c"GitHub.com"}, {~c"vary", ~c"X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With"}, {~c"content-length", ~c"246198"}, {~c"content-type", ~c"text/html; charset=utf-8"}, {~c"strict-transport-security", ~c"max-age=31536000; includeSubdomains; preload"}, {~c"x-frame-options", ~c"deny"}, {~c"x-content-type-options", ~c"nosniff"}, {~c"x-xss-protection", ~c"0"}, {~c"referrer-policy", ~c"no-referrer-when-downgrade"}, {~c"content-security-policy", ~c"default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com api.githubcopilot.com objects-origin.githubusercontent.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/"}, {~c"x-github-request-id", ~c"C1E1:5A5EB:3543835:4BB4B00:660E0274"}], "\n\n\n\n\n\n<!DOCTYPE html>\n<html\n  lang=\"en\"\n  \n  data-color-mode=\"auto\" data-light-theme=\"light\" data-dark-theme=\"dark\"\n  data-a11y-animated-images=\"system\" data-a11y-link-underlines=\"true\"\n  >\n\n\n\n\n  <head>\n    <meta charset=\"utf-8\">\n  <link rel=\"dns-prefetch\" href=\"https://github.githubassets.com\">\n  <link rel=\"dns-prefetch\" href=\"https://avatars.githubusercontent.com\">\n  <link rel=\"dns-prefetch\" href=\"https://github-cloud.s3.amazonaws.com\">\n  <link rel=\"dns-prefetch\" href=\"https://user-images.githubusercontent.com/\">\n  <link rel=\"preconnect\" href=\"https://github.githubassets.com\" crossorigin>\n  <link rel=\"preconnect\" href=\"https://avatars.githubusercontent.com\">\n\n  \n\n  <link crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" href=\"https://github.githubassets.com/assets/light-0eace2597ca3.css\" /><link crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" href=\"https://github.githubassets.com/assets/dark-a167e256da9c.css\" /><link data-color-theme=\"dark_dimmed\" crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" data-href=\"https://github.githubassets.com/assets/dark_dimmed-d11f2cf8009b.css\" /><link data-color-theme=\"dark_high_contrast\" crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" data-href=\"https://github.githubassets.com/assets/dark_high_contrast-ea7373db06c8.css\" /><link data-color-theme=\"dark_colorblind\" crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" data-href=\"https://github.githubassets.com/assets/dark_colorblind-afa99dcf40f7.css\" /><link data-color-theme=\"light_colorblind\" crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" data-href=\"https://github.githubassets.com/assets/light_colorblind-af6c685139ba.css\" /><link data-color-theme=\"light_high_contrast\" crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" data-href=\"https://github.githubassets.com/assets/light_high_contrast-578cdbc8a5a9.css\" /><link data-color-theme=\"light_tritanopia\" crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" data-href=\"https://github.githubassets.com/assets/light_tritanopia-5cb699a7e247.css\" /><link data-color-theme=\"dark_tritanopia\" crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" data-href=\"https://github.githubassets.com/assets/dark_tritanopia-9b32204967c6.css\" />\n    <link crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" href=\"https://github.githubassets.com/assets/primer-primitives-366b5c973fad.css\" />\n    <link crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" href=\"https://github.githubassets.com/assets/primer-44fa1513ddd0.css\" />\n    <link crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" href=\"https://github.githubassets.com/assets/global-dc4670c5d15d.css\" />\n    <link crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" href=\"https://github.githubassets.com/assets/github-f1c434a52a69.css\" />\n  <link crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" href=\"https://github.githubassets.com/assets/repository-6247ca238fd4.css\" />\n<link crossorigin=\"anonymous\" media=\"all\" rel=\"stylesheet\" href=\"https://github.githubassets.com/assets/releases-440cf08f49fc.css\" />\n\n  \n\n\n  <script type=\"application/json\" id=\"client-env\">{\"locale\":\"en\",\"featureFlags\":[\"code_vulnerability_scanning\",\"copilot_conversational_ux_history_refs\",\"copilot_smell_icebreaker_ux\",\"copilot_implicit_context\",\"failbot_handle_non_errors\",\"geojson_azure_maps\",\"image_metric_tracking\",\"marketing_forms_api_integration_contact_request\",\"marketing_pages_search_explore_provider\",\"turbo_experiment_risky\",\"sample_network_conn_type\",\"no_character_key_shortcuts_in_inputs\",\"react_start_transition_for_navigations\",\"custom_inp\",\"remove_child_patch\"]}</script>\n<script crossorigin=\"anonymous\" defer=\"defer\" type=\"application/javascript\" src=\"https://github.githubassets.com/assets/wp-runtime-63a6f9ba35d7.js\"></script>\n<script crossorigin=\"anonymous\" defer=\"defer\" type=\"application/javascript\" src=\"https://github.githubassets.com/assets/vendors-node_modules_dompurify_dist_purify_js-6890e890956f.js\"></script>\n<script crossorigin=\"anonymous\" defer=\"defer\" type=\"application/javascript\" src=\"https://github.githubassets.com/assets/vendors-node_modules_oddbird_popove" <> ...}}
    (adbc 0.3.0) lib/adbc.ex:131: Adbc.download_driver!/2
    #cell:xdggyrpe2mmwf352:1: (file)
```

However I download 0.2.3 and it worked no problem!

Also hi elixir community. I'm exploring the ecosystem right now and it's really awesome. Thanks for making all of these wonderful packages. I look forward to participating in the coming months :)

### PR DESCRIPTION
**Pull request by lkarthee**
fixes #60

### CODE REVIEW

**Comment by lkarthee** [comment]
Release candidates don't have the drivers - https://github.com/apache/arrow-adbc/releases/tag/apache-arrow-adbc-0.11.0-rc0 does not have any artefacts. 

We should not use rc build tags  in update.exs ?

**Comment by cocoa-xu** [comment]
I think the drives were indeed there when we released v0.3.0, https://github.com/elixir-explorer/adbc/actions/runs/8497595927/job/23276329142#step:5:278, otherwise `mix test` wouldn't success on CI. It's likely that arrow-adbc changed the URL after that. 🤔

Other than that, this PR looks good to me!

**Review by cocoa-xu — APPROVED** [review]

**Comment by lkarthee** [comment]
True, that's what I was thinking. Did they rename 0.11.0-rc0 to 0.11.0 ? I made the observation after looking at their old rc releases - hence my observation that we should not use rc tags.

**Comment by cocoa-xu** [comment]
> Did they rename 0.11.0-rc0 to 0.11.0?

Probably this was what happened. 0.11.0-rc0 is now officially the first version of 0.11.0.

> hence my suggestion that we should not use rc tags.

Or we can name the pre-released rc versions, like 0.11.0-rc1, in something like v0.3.2-rc1 in the future. So it's also a pre-release version on hex.pm.

**Comment by josevalim** [comment]
I don’t think we need to track releases that closely unless we need to test a feature, so I would say we should track releases only and ignore pre.

**Pull request merged**
