### PR TITLE
Add support for decimal values

### PR DESCRIPTION
**Pull request by cocoa-xu**
This draft PR adds support for decoding decimal values from Arrow streams. 

But I'm kinda confused about the encoding part -- how to translate an arbitrary `Decimal.t()` to an `ArrowDecimal` with the given precision and scale... 

I was wondering if you by any chance have any hints or suggestions @josevalim?

### CODE REVIEW

**Comment by josevalim** [comment]
@cocoa-xu Can you tell me a bit more about the format that is expected by arrow here? How does it represent the Decimal internally?

And maybe this code from Postgrex can be of help? https://github.com/elixir-ecto/postgrex/blob/ef6bd2f2d6c385af0347330cc159be05a458ab8c/lib/postgrex/extensions/numeric.ex#L32

**Comment by cocoa-xu** [comment]
> @cocoa-xu Can you tell me a bit more about the format that is expected by arrow here? How does it represent the Decimal internally?

Ah of course! It's expected to be a 128-bit little-endian integer for the decimal128 type, and the integer is scaled. For example, 

`12.345` is represented as `12345` in a 128-bit little-endian integer with `precision=5` and `scale=3`,

```
12345=12.345*10^3
```

The value of `precision` means the number of significant digits. So, basically, it's `integer=decimal * :math.pow(10, scale)`.

I was a bit confused about the cases like how we should encode the number if the user specify `precision=4` and `scale=3` for `12.345`. But I just tried their python implementation and they simply would raise an exception if the rescaling would cause data loss:

```python
>>> import decimal
>>> import pyarrow as pa
>>> a = decimal.Decimal('12.345')
>>> 
>>> # raise if not fit
>>> pa.array([a], pa.decimal128(4, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 355, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Rescaling Decimal128 value would cause data loss
>>>
>>> # ok
>>> pa.array([a], pa.decimal128(5, 3))
<pyarrow.lib.Decimal128Array object at 0x104fc9cc0>
[
  12.345
]
>>> # also ok if the precision number is higher
>>> pa.array([a], pa.decimal128(7, 3))
<pyarrow.lib.Decimal128Array object at 0x104fc9cc0>
[
  12.345
]
```

**Comment by cocoa-xu** [comment]
And it seems that `pyarrow` won't allow `Inf`, `-Inf` or `NaN`.

```python
>>> a = decimal.Decimal('Inf')
>>> a
Decimal('Infinity')
>>> pa.array([a], pa.decimal128(7, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 355, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: The string 'Infinity' is not a valid decimal128 number
```

So perhaps we need to do the same in `Adbc.Column.decimal{128,256}`:
- iterate through the given list
- raise if there are any `Inf`, `-Inf` or `NaN`
- convert each decimal to a 128- or 256-bit little endian integer if it fits the given precision and scale
- and further convert them into their binary representation so we can read them in C

I guess this sounds good?

**Comment by cocoa-xu** [comment]
I also added some tests for `Adbc.Column.decimal{128,256}/4`. Hope it looks okay to you, and please let me know if I missed any corner cases. :)

**Review by josevalim — APPROVED** [review]
LGTM! I wonder if we should also have an API that works directly with large integers instead of Decimal, since we end-up converting them into a large integer anyway?

**Comment by cocoa-xu** [comment]
> I wonder if we should also have an API that works directly with large integers instead of Decimal, since we end-up converting them into a large integer anyway?

Surely! I'll add support for that

**Comment by josevalim** [comment]
@cocoa-xu but we can do that in another PR if you prefer, to keep this one focused. :)

**Comment by cocoa-xu** [comment]
> @cocoa-xu but we can do that in another PR if you prefer, to keep this one focused. :)

That works too! It should be a relatively small PR :)

**Pull request merged**
