### PR TITLE
[nif]: out-of-bound access in get_arrow_array_children_as_list

### PR DESCRIPTION
**Pull request by cocoa-xu**

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

**Comment by cocoa-xu** [comment]
It didn't stop at the 2-minute mark, so perhaps I should also set `connect_timeout`. And if it failed to connect to github.com, it could be a DNS issue?

**Comment by josevalim** [comment]
connect_timeout is a good call, yeah.

**Comment by cocoa-xu** [comment]
So it [can download v0.4.0](https://github.com/elixir-explorer/adbc/actions/runs/5598638012/jobs/10238543860#step:5:311) and start testing but not v0.5.1.

**Comment by cocoa-xu** [comment]
Tests that passed:
#### start_link
- `test/adbc_connection_test.exs:13`
- `test/adbc_connection_test.exs:18`
- `test/adbc_connection_test.exs:26`
- `test/adbc_connection_test.exs:34`

#### query
- `test/adbc_connection_test.exs:170`

Tests that failed: 

they all failed with error message `vector subscript out of range`

Screenshot 2023-07-19 at 13 01 12

#### get_info
- `test/adbc_connection_test.exs:44`
- `test/adbc_connection_test.exs:65`

#### get_objects
- `test/adbc_connection_test.exs:87`

#### get_table_types
- `test/adbc_connection_test.exs:143`

#### query
- `test/adbc_connection_test.exs:153`
- `test/adbc_connection_test.exs:163`

#### lock
- `test/adbc_connection_test.exs:190`
- `test/adbc_connection_test.exs:199`
- `test/adbc_connection_test.exs:211`
- `test/adbc_connection_test.exs:228`

**Review by josevalim — APPROVED** [review]
Lets remove the timeouts and ship it!

**Pull request merged**
